### ISSUE TITLE
Project automation

### ISSUE THREAD

**Issue by jmesmon** [meta-rust/meta-rust#74]
- [ ] auto-assign PRs to someone with commit access
- [ ] auto-assign Issues so someone is pinged to glance at them
- [ ] build testing (travis? buildbot host? something else?)
- [ ] bors/homu/etc like setup for merging PRs.

**Comment by derekstraka** [comment]
IIRC the travis builds we were originally working on timed out because it took so long to build all of the rust items.

**Comment by cardoe** [comment]
So I setup some more protected branches (for each of the Yocto releases) and for master set the requirement that the PR passed through Jenkins and is up to date with master.

**Comment by cardoe** [comment]
Played around with homu a bit. Its dependent on Travis, which won't work for us due to the build times. bors is the closed source version of homu.

**Comment by jmesmon** [comment]
bors is (IIRC), the old version: https://github.com/graydon/bors

There is also a re-write of homu in rust somewhere (I'm looking), but I'm not sure who is using it.
